package com.clinica.abc.common;

public enum SessionValue {
  NEXT_STEP,
  CURRENT_USER,

  SHOW_INTRO,

  AVAILABLE_SCHEDULES,
  AVAILABLE_SCHEDULES_FINISHED,

  SELECTED_SCHEDULE,

  SET_APPOINTMENT_FINISHED,
  SET_APPOINTMENT_FINISHED_OK,

  SCHEDULES_BY_USER,
  SCHEDULES_BY_USER_FINISHED
}
