package com.clinica.abc.common;

public enum SessionValue {
  NEXT_STEP,
  CURRENT_USER,

  SCHEDULES_DATES,
  SCHEDULES_DATES_FINISHED,

  SELECTED_DATE,
  SELECTED_HOUR,

  SET_APPOINTMENT_FINISHED,
  SET_APPOINTMENT_FINISHED_OK
}
